# Generated by Django 2.1 on 2022-07-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0002_auto_20220716_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunks',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE')], max_length=10),
        ),
    ]
