# Generated by Django 2.1 on 2022-07-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0003_auto_20220716_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunks',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('german', 'GERMAN')], max_length=10),
        ),
    ]
