# Generated by Django 2.1 on 2022-07-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0004_auto_20220717_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunks',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chunkslinks',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks_watch_link', to='chunks.chunks'),
        ),
    ]
