# Generated by Django 2.1 on 2022-07-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0005_auto_20220717_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunks',
            name='movie_trailer',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
