# Generated by Django 2.1 on 2022-07-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0009_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video_file',
            new_name='chunks_file',
        ),
        migrations.AddField(
            model_name='chunkslinks',
            name='content',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
