# Generated by Django 2.1 on 2022-07-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0010_auto_20220722_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='chunkslinks',
            name='content',
        ),
    ]
