# Generated by Django 2.1 on 2022-07-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0012_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
