# Generated by Django 2.1 on 2022-07-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0014_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
